### ISSUE TITLE
Backlight on Hold options are ignored.

### ISSUE THREAD

**Issue by razzintown** [ilikenwf/rockbox-ipod6g#1]
Menu Location:
Settings -> General -> Display -> SCD Settings -> Backlight on Hold -> (All options)

Problem:
All options are ignored.

Expected Behavior:
I typically use "Off", so that the screen immediately turns off/on when flipping the hold switch on/off respectively.

Last Working Build:
I had been using ce714cb-130818.

**Comment by ilikenwf** [comment]
I just pulled in a commit from the gerrit that fixes this - you didn't happen to make the fix, did you?

**Comment by razzintown** [comment]
Sorry I missed this. I did not make it.
